### ISSUE TITLE
Dual-license with more mature license

### ISSUE THREAD

**Issue by Nameguy** [quartzjer/js0n#16]
The Unlicense is known among software lawyers for being a bit sketchy. Large companies are advised by their lawyers that they can't afford to take Unlicensed software seriously. This is a big shame, because the Unlicense stands for something very significant and we should take strides to improve its legal status, but in the meantime, one could do with a workaround. I suggest the [MIT license](https://opensource.org/licenses/MIT) be used.

[LICENSE.txt](https://github.com/quartzjer/js0n/files/497121/LICENSE.txt)

**Comment by quartzjer** [comment]
Great idea, should have been MIT from the start, thanks!

**Comment by quapaso345** [comment]
@Nameguy  this was a stupid request for a stupid license. You're so keen on following mainstream propaganda and all this "license" garbage. Shame on you.

**Comment by quapaso345** [comment]
@Nameguy  this was a stupid request for a stupid license.

 You're so keen on following mainstream propaganda and all this "license" garbage. Shame on you.

**Comment by quapaso345** [comment]
@Nameguy  this was a stupid request for a stupid license. You're so keen on following mainstream propaganda and all this "license" garbage. 

Shame on you.@Nameguy
